CNL: cnl Namespace Reference
cnl Namespace Reference
compositional numeric library
Namespaces
literals
user-defined literals
numbers
compositional numeric library, numbers header/namespace
Classes
struct constant
type whose value is also its non-type template parameter
struct custom_operator
customization point for operator overloads
struct custom_operator< _impl::convert_op, op_value< Input, _impl::native_tag >, op_value< scaled_integer< ResultRep, power< ResultExponent, ResultRadix > >, neg_inf_rounding_tag > >
cnl::neg_inf_rounding_tag
struct custom_operator< _impl::convert_op, op_value< Input, _impl::native_tag >, op_value< scaled_integer< ResultRep, power< ResultExponent, ResultRadix > >, tie_to_pos_inf_rounding_tag > >
cnl::tie_to_pos_inf_rounding_tag
struct custom_operator< _impl::convert_op, op_value< Input, nearest_rounding_tag >, op_value< Result, power< 0, Radix > > >
cnl::nearest_rounding_tag
struct fraction
numeric type represented as the fraction, numerator / denominator
struct from_rep
generic function object that returns the number encapsulating a given value
struct from_rep< Number, Rep >
Specialization of from_rep for integer types.
struct from_rep< scaled_integer< ArchetypeRep, power< Exponent, Radix > >, Rep >
scaled_integer specialization of from_rep
struct native_overflow_tag
tag to match the overflow behavior of fundamental arithmetic types
struct native_rounding_tag
tag to match the rounding behavior of fundamental arithmetic types
struct nearest_rounding_tag
tag to specify round-to-nearest behavior in arithemtic operations
struct neg_inf_rounding_tag
tag to specify floor or round towards minus infinity rounding behavior in arithmetic operations
class op_value
operand or result of operation;used as Operands parameter of cnl::custom_operator
struct rep_of
meta-function object that returns the Rep type of a component
struct rounding
given a numeric type, defines member type as its rounding mode
struct saturated_overflow_tag
tag to match the overflow behavior of fundamental arithmetic types
struct set_digits
convert a type to a similar type with the given number of digits
struct set_rep
meta-function object that transforms a component from one Rep type to another
struct set_rep< elastic_integer< Digits, Narrowest >, Rep >
elastic_integer specialization of set_rep
struct set_rounding
given a numeric type, defines member type as the equivalent type with the given rounding mode User-specializations of this type are permitted.
struct set_tag
meta-function object that transforms a component from one Tag type to another
struct set_tag< elastic_integer< Digits, Narrowest >, elastic_tag< NewDigits, NewNarrowest > >
elastic_integer specialization of set_tag
struct tag_of
meta-function object that returns the Tag type of a component
struct throwing_overflow_tag
tag to specify throw-on-overflow behavior in arithemtic operations
struct tie_to_pos_inf_rounding_tag
tag to specify tie to positive inf rounding behavior in arithmetic operations
struct to_rep
Returns the value encapsulated in number.
struct trapping_overflow_tag
tag to specify trap-on-overflow behavior in arithemtic operations
struct undefined_overflow_tag
tag to specify undefined-behavior-on-overflow behavior in arithemtic operations
Typedefs
template<int Digits = digits<int>, integer Narrowest = int>
using elastic_integer = _impl::wrapper< typename elastic_tag< Digits, Narrowest >::_rep, elastic_tag< Digits, Narrowest > >
An integer type with auto-widening operators.
template<int Digits, int Exponent = 0, class Narrowest = signed>
using elastic_scaled_integer = scaled_integer< elastic_integer< Digits, Narrowest >, power< Exponent > >
literal real number approximation that uses fixed-point arithmetic and auto-widens to avoid overflow
template<unsigned NumDigits = digits<int>>
using multiprecision = signed_multiprecision< NumDigits >
alias to a signed, fixed-size Boost.Multiprecision type suitable for specializing cnl::scaled_integer
template<typename Rep = int, overflow_tag Tag = undefined_overflow_tag>
using overflow_integer = _impl::wrapper< Rep, Tag >
An integer which detects overflow.
template<typename Rep = int, rounding_tag Tag = nearest_rounding_tag>
using rounding_integer = _impl::wrapper< Rep, Tag >
An integer which detects overflow.
template<typename Number >
using rounding_t = typename rounding< Number >::type
helper alias of cnl::rounding
template<integer Rep = int, class Scale = power<>>
using scaled_integer = _impl::wrapper< Rep, Scale >
literal real number approximation that uses fixed-point arithmetic
template<class T , int Digits>
using set_digits_t = typename set_digits< T, Digits >::type
Alias to cnl::set_digits.
template<typename Number , rounding_tag RoundingTag>
using set_rounding_t = typename set_rounding< Number, RoundingTag >::type
helper alias of cnl::set_rounding
template<unsigned NumDigits = digits<int>>
using signed_multiprecision = _sized_integer_impl::number< NumDigits+1, _bmp::signed_magnitude >
alias to a signed, fixed-size Boost.Multiprecision type suitable for specializing cnl::scaled_integer
template<int Digits = digits<int>, rounding_tag RoundingTag = nearest_rounding_tag, overflow_tag OverflowTag = undefined_overflow_tag, class Narrowest = int>
using static_integer = _impl::static_integer< Digits, RoundingTag, OverflowTag, Narrowest >
a general-purpose integer type
template<int Digits, int Exponent = 0, rounding_tag RoundingTag = nearest_rounding_tag, overflow_tag OverflowTag = undefined_overflow_tag, class Narrowest = signed>
using static_number = scaled_integer< _impl::static_integer< Digits, RoundingTag, OverflowTag, Narrowest >, power< Exponent > >
a general-purpose fixed-point real number type
template<unsigned NumDigits = digits<unsigned>>
using unsigned_multiprecision = _sized_integer_impl::number< NumDigits, _bmp::unsigned_magnitude >
alias to an unsigned, fixed-size Boost.Multiprecision type suitable for specializing cnl::scaled_integer
template<int Digits = digits<int>, typename Narrowest = int>
using wide_integer = _impl::wrapper< typename wide_tag< Digits, Narrowest >::rep, wide_tag< Digits, Narrowest > >
An integer of limitless width.
Functions
template<typename Rep , class Scale >
constexpr auto abs (scaled_integer< Rep, Scale > const &x) noexcept -> decltype(-x)
absolute value
template<tag Tag, typename Lhs , typename Rhs >
constexpr auto add (Lhs const &lhs, Rhs const &rhs)
adds two values together
template<tag DestTag, tag SrcTag, typename Dest , typename Src >
constexpr auto convert (Src const &src)
converts a value to a type
template<tag Tag, typename Lhs , typename Rhs >
constexpr auto divide (Lhs const &lhs, Rhs const &rhs)
divides one value by another
template<class Rep , int Exponent>
constexpr auto exp2 (scaled_integer< Rep, power< Exponent >> x) -> scaled_integer< Rep, power< Exponent >>
Calculates exp2(x), i.e. 2^xAccurate to 1LSB for up to 32 bit underlying representation.
template<typename Narrowest = int, ::cnl::intmax Value = 0>
constexpr auto make_elastic_scaled_integer (constant< Value >) -> elastic_scaled_integer< std::max(digits< constant< Value >> - trailing_bits(Value), 1), trailing_bits(Value), Narrowest >
generate an cnl::elastic_scaled_integer object of given value
template<typename Narrowest = void, typename Integral = int>
constexpr auto make_elastic_scaled_integer (Integral const &value) -> elastic_scaled_integer< numeric_limits< Integral >::digits, 0, typename std::conditional< std::is_same< void, Narrowest >::value, _impl::adopt_signedness_t< int, Integral >, Narrowest >::type >
generate an cnl::elastic_scaled_integer object of given value
template<typename Value >
constexpr auto make_scaled_integer (Value const &value)
makes a scaled_integer object from a given value
template<rounding_tag RoundingTag = _impl::tag_of_t<rounding_integer<>>, overflow_tag OverflowTag = _impl::tag_of_t<overflow_integer<>>, class Narrowest = int, class Input = int, ::cnl::intmax Value>
constexpr auto make_static_number (constant< Value > const &) -> static_number< _impl::used_digits(Value) - trailing_bits(Value), trailing_bits(Value), RoundingTag, OverflowTag, Narrowest >
constructs a static_number from a given constant value
template<rounding_tag RoundingTag = nearest_rounding_tag, overflow_tag OverflowTag = undefined_overflow_tag, class Narrowest = signed, class Input = int>
constexpr auto make_static_number (Input const &input) -> static_number< numeric_limits< Input >::digits, 0, RoundingTag, OverflowTag, Narrowest >
constructs a static_number from a given variable
template<tag Tag, typename Lhs , typename Rhs >
constexpr auto multiply (Lhs const &lhs, Rhs const &rhs)
multiplies one value by another
template<int LhsExponent, int RhsExponent, int Radix>
constexpr auto operator+ (power< LhsExponent, Radix >, power< RhsExponent, Radix >) -> power< std::min(LhsExponent, RhsExponent), Radix >
value of template parameter, Exponent
template<class Dividend , class Divisor >
constexpr auto quotient (Dividend const &dividend, Divisor const &divisor)
calculates the quotient of two scaled_integer values
template<tag Tag, typename Lhs , typename Rhs >
constexpr auto shift_right (Lhs const &lhs, Rhs const &rhs)
bitwise left-shifts one value by another
template<int Digits, class Narrowest >
constexpr auto sqrt (elastic_integer< Digits, Narrowest > const &x)
elastic_integer overload of cnl::sqrt
template<integer Integer>
constexpr auto sqrt (Integer const &x)
integer overload of cnl::sqrt
template<typename Rep , int Exponent, int Radix>
constexpr auto sqrt (scaled_integer< Rep, power< Exponent, Radix >> const &x)
scaled_integer overload of cnl::sqrt
template<tag Tag, typename Lhs , typename Rhs >
constexpr auto subtract (Lhs const &lhs, Rhs const &rhs)
subtracts one value from another
Variables
template<typename T >
constexpr int digits = 0
provide number of binary digits of the given type
Detailed Description
compositional numeric library
Typedef Documentation
elastic_integer
template<int Digits = digits<int>, integer Narrowest = int> using cnl::elastic_integer = typedef _impl::wrapper< typename elastic_tag<Digits, Narrowest>::_rep, elastic_tag<Digits, Narrowest> >
An integer type with auto-widening operators.
Template Parameters
Digits a count of the number of digits needed to express the number
Narrowest the most narrow integer type to use for storage
Note
The value is stored in an object of Narrowest or cnl::set_digits_t<Narrowest, Digits>.
Arithmetic operations result in types with an adjusted Digits parameter accordingly. For instance, when two elastic_integer values are multiplied together, the resultant type has Digits set to the sum of the operands.
See also
cnl::elastic_scaled_integer
elastic_scaled_integer
template<int Digits, int Exponent = 0, class Narrowest = signed> using cnl::elastic_scaled_integer = typedef scaled_integer<elastic_integer<Digits, Narrowest>, power<Exponent> >
literal real number approximation that uses fixed-point arithmetic and auto-widens to avoid overflow
Template Parameters
Digits the total number of integer and fractional digits stored
Exponent the exponent by which the number is scale
Narrowest the most narrow integer type to use to represent values
See also
elastic_integer
multiprecision
template<unsigned NumDigits = digits<int>> using cnl::multiprecision = typedef signed_multiprecision<NumDigits>
alias to a signed, fixed-size Boost.Multiprecision type suitable for specializing cnl::scaled_integer
Template Parameters
NumDigits number of digits constituting the integer value (excluding sign bit)
See also
cnl::signed_multiprecision, cnl::unsigned_multiprecision
rounding_t
template<typename Number > using cnl::rounding_t = typedef typename rounding<Number>::type
helper alias of cnl::rounding
See also
cnl::rounding, cnl::set_rounding_t, cnl::native_rounding_tag, cnl::nearest_rounding_tag
scaled_integer
template<integer Rep = int, class Scale = power<>> using cnl::scaled_integer = typedef _impl::wrapper<Rep, Scale>
literal real number approximation that uses fixed-point arithmetic
Template Parameters
Rep the underlying type used to represent the value; defaults to int
Exponent the exponent used to scale the integer value; defaults to 0
Radix the base used to scale the integer value; defaults to radix of Rep
Uses an integer to approximate a real number. Scales the integer by pow(Radix, Exponent) to produce the scaled number. By default, represents an int with no fractional digits using binary arithmetic.
Note
Currently, only binary support and partial decimal support is tested.
The type makes no effort to avoid errors resulting from overflow or underflow. Consider specializing with:
rounding_integer to reduce precision loss;
elastic_integer to avoid out-of-range errors;
overflow_integer to detect out-of-range errors; and
static_integer to combine all of the above.
Examples
To define a fixed-point value 1 byte in size with a sign bit, 4 integer bits and 3 fractional bits:
        constexpr auto n = scaled_integer<std::int8_t, power<-3>>{-2.75};
        static_assert(n == -2.75, "fixed-point type was unable to store the value");
set_rounding_t
template<typename Number , rounding_tag RoundingTag> Tag cnl::set_rounding_t< _impl::rep_of_t< Number >, Tag >
Initial value:
{
    }
helper alias of cnl::set_rounding
See also
cnl::set_rounding, cnl::rounding_t, cnl::native_rounding_tag, cnl::nearest_rounding_tag
signed_multiprecision
template<unsigned NumDigits = digits<int>> using cnl::signed_multiprecision = typedef _sized_integer_impl::number<NumDigits + 1, _bmp::signed_magnitude>
alias to a signed, fixed-size Boost.Multiprecision type suitable for specializing cnl::scaled_integer
Template Parameters
NumDigits number of digits constituting the integer value (excluding sign bit)
See also
cnl::unsigned_multiprecision, cnl::multiprecision
static_integer
template<int Digits = digits<int>, rounding_tag RoundingTag = nearest_rounding_tag, overflow_tag OverflowTag = undefined_overflow_tag, class Narrowest = int> using cnl::static_integer = typedef _impl::static_integer<Digits, RoundingTag, OverflowTag, Narrowest>
a general-purpose integer type
Template Parameters
Digits number of binary digits
OverflowTag behavior exhibited on out-of-range conditions
RoundingTag behavior exhibited on precision loss
Narrowest narrowest integer with which to represent the value
See also
cnl::static_number
static_number
template<int Digits, int Exponent = 0, rounding_tag RoundingTag = nearest_rounding_tag, overflow_tag OverflowTag = undefined_overflow_tag, class Narrowest = signed> using cnl::static_number = typedef scaled_integer< _impl::static_integer<Digits, RoundingTag, OverflowTag, Narrowest>, power<Exponent> >
a general-purpose fixed-point real number type
Template Parameters
Digits number of binary digits
Exponent the exponent used to scale the integer value
OverflowTag behavior exhibited on out-of-range conditions
RoundingTag behavior exhibited on precision loss
Narrowest narrowest integer with which to represent the value
See also
cnl::static_integer
unsigned_multiprecision
template<unsigned NumDigits = digits<unsigned>> using cnl::unsigned_multiprecision = typedef _sized_integer_impl::number<NumDigits, _bmp::unsigned_magnitude>
alias to an unsigned, fixed-size Boost.Multiprecision type suitable for specializing cnl::scaled_integer
Template Parameters
NumDigits number of digits constituting the integer value (excluding sign bit)
See also
cnl::signed_multiprecision, cnl::multiprecision
Function Documentation
abs()
template<typename Rep , class Scale > constexpr auto cnl::abs (scaled_integer< Rep, Scale > const & x) -> decltype(-x) constexpr noexcept
absolute value
Parameters
x input parameter
Returns
|x|
See also
std::abs
add()
template<tag Tag, typename Lhs , typename Rhs > constexpr auto cnl::add (Lhs const & lhs, Rhs const & rhs) constexpr
adds two values together
Template Parameters
Tag specifies the conversion mode, e.g. cnl::native_overflow_tag
Returns
the result of lhs + rhs
See also
cnl::convert, cnl::divide, cnl::shift_right, cnl::multiply, cnl::subtract, cnl::native_overflow_tag, cnl::saturated_overflow_tag, cnl::throwing_overflow_tag, cnl::trapping_overflow_tag, cnl::undefined_overflow_tag, cnl::nearest_rounding_tag
convert()
template<tag DestTag, tag SrcTag, typename Dest , typename Src > constexpr auto cnl::convert (Src const & src) constexpr
converts a value to a type
Template Parameters
DestTag specifies the destination behavior tag, e.g. cnl::native_overflow_tag
SrcTag specifies the source behavior tag, e.g. cnl::native_overflow_tag
Parameters
src value to convert from
Returns
value converted to
See also
cnl::add, cnl::divide, cnl::shift_right, cnl::multiply, cnl::subtract, cnl::native_overflow_tag, cnl::saturated_overflow_tag, cnl::throwing_overflow_tag, cnl::trapping_overflow_tag, cnl::undefined_overflow_tag, cnl::nearest_rounding_tag
divide()
template<tag Tag, typename Lhs , typename Rhs > constexpr auto cnl::divide (Lhs const & lhs, Rhs const & rhs) constexpr
divides one value by another
Template Parameters
Tag specifies the conversion mode, e.g. cnl::native_rounding_tag
Returns
the result of lhs / rhs
See also
cnl::add, cnl::convert, cnl::shift_right, cnl::multiply, cnl::subtract, cnl::native_overflow_tag, cnl::saturated_overflow_tag, cnl::throwing_overflow_tag, cnl::trapping_overflow_tag, cnl::undefined_overflow_tag, cnl::nearest_rounding_tag
exp2()
template<class Rep , int Exponent> constexpr auto cnl::exp2 (scaled_integer< Rep, power< Exponent >> x) -> scaled_integer<Rep, power<Exponent>> constexpr
Calculates exp2(x), i.e. 2^xAccurate to 1LSB for up to 32 bit underlying representation.
Template Parameters
x the input value as a scaled_integer
Returns
the result of the exponential, in the same representation as x
make_elastic_scaled_integer() [1/2]
template<typename Narrowest = int, ::cnl::intmax Value = 0> constexpr auto cnl::make_elastic_scaled_integer (constant< Value >) -> elastic_scaled_integer< std::max(digits<constant<Value>> - trailing_bits(Value), 1), trailing_bits(Value), Narrowest> constexpr
generate an cnl::elastic_scaled_integer object of given value
Template Parameters
Narrowest the narrowest type to use as storage in the resultant cnl::elastic_scaled_integer object
Integral the type of Value
Value the integer number to be represented
Returns
the given value to be represented using an cnl::elastic_scaled_integer type
Note
The return type is guaranteed to be no larger than is necessary to represent the value.
Example
To define an int-sized object using make_elastic_scaled_integer and cnl::constant
        // std::uint8_t specifies the type of const_integer - not elastic
        constexpr auto n = make_elastic_scaled_integer(constant<0xAA>{});
        static_assert(n == 0xAA, "n now has the value, 1024");
        static_assert(
                std::is_same<decltype(n), elastic_scaled_integer<7, 1, int> const>::value,
                "by default make_elastic_scaled_integer uses the most efficient type it can");
make_elastic_scaled_integer() [2/2]
template<typename Narrowest = void, typename Integral = int> constexpr auto cnl::make_elastic_scaled_integer (Integral const & value) -> elastic_scaled_integer< numeric_limits<Integral>::digits, 0, typename std::conditional< std::is_same<void, Narrowest>::value, _impl::adopt_signedness_t<int, Integral>, Narrowest>::type> constexpr
generate an cnl::elastic_scaled_integer object of given value
Template Parameters
Narrowest the most narrow storage type of the resultant cnl::elastic_scaled_integer object
Integral the type of value
Parameters
value the value with which to initialize the elastic_scaled_integer object
Note
The return type is guaranteed to be no larger than is necessary to represent the value.
Example
To define a byte-sized object using make_elastic_scaled_integer and _c:
        constexpr auto n = make_elastic_scaled_integer<char>(constant<1536>{});
        static_assert(n == 1536, "n now has the value, 1536");
        static_assert(
                std::is_same<decltype(n), elastic_scaled_integer<2, 9, char> const>::value,
                "by default make_elastic_scaled_integer uses the most efficient type it can");
make_scaled_integer()
template<typename Value > constexpr auto cnl::make_scaled_integer (Value const & value) constexpr
makes a scaled_integer object from a given value
Template Parameters
Value the type of the value that is to be made into a scaled_integer value
Parameters
value the value from which to make the scaled_integer object
Note
This function is deprecated after C++17 in favor of class template deduction.
Referenced by quotient().
multiply()
template<tag Tag, typename Lhs , typename Rhs > constexpr auto cnl::multiply (Lhs const & lhs, Rhs const & rhs) constexpr
multiplies one value by another
Template Parameters
Tag specifies the conversion mode, e.g. cnl::native_overflow_tag
Returns
the result of lhs + rhs
See also
cnl::add, cnl::convert, cnl::divide, cnl::subtract, cnl::shift_right, cnl::native_overflow_tag, cnl::saturated_overflow_tag, cnl::throwing_overflow_tag, cnl::trapping_overflow_tag, cnl::undefined_overflow_tag, cnl::nearest_rounding_tag
quotient()
template<class Dividend , class Divisor > constexpr auto cnl::quotient (Dividend const & dividend, Divisor const & divisor) constexpr
calculates the quotient of two scaled_integer values
Template Parameters
Dividend the dividend (top number) of the division
Divisor the divisor (bottom number) of the division
Parameters
dividend,divisor dividend and divisor
Returns
quotient: dividend / divisor
Note
This function provides 'quasi-exact' division as described in P1368.
References make_scaled_integer().
shift_right()
template<tag Tag, typename Lhs , typename Rhs > constexpr auto cnl::shift_right (Lhs const & lhs, Rhs const & rhs) constexpr
bitwise left-shifts one value by another
Template Parameters
Tag specifies the conversion mode, e.g. cnl::native_overflow_tag
Returns
the result of lhs + rhs
See also
cnl::add, cnl::convert, cnl::divide, cnl::multiply, cnl::subtract, cnl::native_overflow_tag, cnl::saturated_overflow_tag, cnl::throwing_overflow_tag, cnl::trapping_overflow_tag, cnl::undefined_overflow_tag, cnl::nearest_rounding_tag
sqrt() [1/3]
template<int Digits, class Narrowest > auto cnl::sqrt (elastic_integer< Digits, Narrowest > const & x) constexpr
elastic_integer overload of cnl::sqrt
Returns
square root of x
Note
This function has O(n) complexity where n is the number of significant digits.
Precondition
x must be non-negative
References sqrt().
sqrt() [2/3]
template<integer Integer> constexpr auto cnl::sqrt (Integer const & x) constexpr
integer overload of cnl::sqrt
Returns
square root of x
Note
This function has O(n) complexity where n is the number of significant digits.
Precondition
x must be non-negative
Referenced by sqrt().
sqrt() [3/3]
template<typename Rep , int Exponent, int Radix> auto cnl::sqrt (scaled_integer< Rep, power< Exponent, Radix >> const & x) constexpr
scaled_integer overload of cnl::sqrt
Returns
square root of x
Note
This function has O(n) complexity where n is the number of significant digits.
Precondition
x must be non-negative
Exponent must be even
References sqrt().
subtract()
template<tag Tag, typename Lhs , typename Rhs > constexpr auto cnl::subtract (Lhs const & lhs, Rhs const & rhs) constexpr
subtracts one value from another
Template Parameters
Tag specifies the conversion mode, e.g. cnl::native_overflow_tag
Returns
the result of lhs - rhs
See also
cnl::add, cnl::convert, cnl::divide, cnl::shift_right, cnl::multiply, cnl::native_overflow_tag, cnl::saturated_overflow_tag, cnl::throwing_overflow_tag, cnl::trapping_overflow_tag, cnl::undefined_overflow_tag, cnl::nearest_rounding_tag
Variable Documentation
digits
template<typename T > constexpr int cnl::digits< _bmp::number< _bmp::cpp_int_backend< NumBits, NumBits, _bmp::unsigned_magnitude > > > = 0 constexpr
provide number of binary digits of the given type
Template Parameters
T the source type
Digits the desired number of digits
Note
does not include a sign bit
See also
cnl::set_digits